# Generated by Django 5.2.11 on 2026-02-17 18:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VehicleRegistry",
            fields=[
                (
                    "plate_number",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("predicted_color", models.CharField(blank=True, max_length=20)),
                ("predicted_type", models.CharField(blank=True, max_length=20)),
                (
                    "owner_status",
                    models.CharField(
                        choices=[
                            ("Clean", "Clean"),
                            ("Stolen", "Stolen"),
                            ("Watchlist", "Watchlist"),
                        ],
                        default="Clean",
                        max_length=20,
                    ),
                ),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SightingLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camera_id",
                    models.CharField(default="CAM_01_TOLL_GATE", max_length=50),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "snapshot_path",
                    models.ImageField(blank=True, null=True, upload_to="snapshots/"),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("weather_condition", models.CharField(default="Clear", max_length=30)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sightings",
                        to="core.vehicleregistry",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
