# Generated by Django 5.2.11 on 2026-02-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sightinglog",
            name="lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sightinglog",
            name="lon",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
