# Generated by Django 5.2.11 on 2026-02-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sightinglog_lat_sightinglog_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("video_path", models.CharField(blank=True, max_length=255)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Online", "Online"), ("Offline", "Offline")],
                        default="Online",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
