# Generated by Django 5.2.11 on 2026-02-19 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_camera"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Camera",
        ),
    ]
